<?xml version='1.0'?>

<robot name="myrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:property name="cameraSize" value="0.05"/>
<xacro:property name="cameraMass" value="0.05"/>


  <xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo" />
  <xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find mybot_description)/urdf/macros.xacro" />

 <!-- Base Size -->
  <property name="base_x_size" value="1" />
  <property name="base_y_size" value="0.5" />
  <property name="base_z_size" value="0.3" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.5120" />
  <xacro:property name="track" value="0.5708" />
  <xacro:property name="wheel_vertical_offset" value="0.03282" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.1" />
  <xacro:property name="wheel_radius" value="0.2" />
  <link name='base_link'>
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="15.0"/>
      <origin xyz="0.0 0 0.1" rpy=" 0 0 0"/>
      <inertia
         ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296"
      />
    </inertial>

    <collision name='collision'>
      <geometry>
        <box size="1 .5 .3"/>
      </geometry>
    </collision>

    <visual name='base_link_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="1 .5 .3"/>
      </geometry>
        <material name="grey"/>
    </visual>
  </link>


    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_footprint" />
    </joint>

    <!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link">
      <inertial>
        <mass value="46.034"/>
        <origin xyz="-0.00065 -0.085 0.062" />
        <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>

  <!--link name="base_footprint">
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.05 0.03" />
      </geometry>

    </visual>
  </link-->

  <!--joint name="base_link_joint" type="fixed">
    <origin xyz="0.0 0 0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint-->
    
  <link name="medium_left_wheel">
    <origin xyz="0 0.3 0.1" rpy="0 1.5707 1.5707"/>
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
    </collision>
    <visual name="medium_left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
        <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.2" h="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <link name="medium_right_wheel">
    <origin xyz="0 -0.3 0.1" rpy="0 1.5707 1.5707"/>
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
    </collision>
    <visual name="medium_right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
        <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.2" h="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <link name="front_left_wheel">
    <collision name="collision">
      <!--origin xyz="0 0 0" rpy="0 1.5707 1.5707"/-->
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
    </collision>
    <visual name="front_left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
        <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.2" h="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <link name="front_right_wheel">
    <collision name="collision">
      <!--origin xyz="0 0 0" rpy="0 1.5707 1.5707"/-->
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
    </collision>
    <visual name="front_right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
        <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.2" h="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

<link name="back_left_wheel">
    <!--origin xyz="0.1 0.13 0.1" rpy="0 1.5707 1.5707"/-->
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
    </collision>
    <visual name="back_left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
        <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.2" h="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>


  <link name="back_right_wheel">
    <!--origin xyz="0.1 -0.13 0.1" rpy="0 1.5707 1.5707"/-->
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
    </collision>
    <visual name="back_right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.2" length="0.1"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <cylinder_inertia m="5" r="0.2" h="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
</link>


 <joint type="continuous" name="medium_left_wheel_hinge">
    <origin xyz="0 0.3 0" rpy="0 0 0"/>
    <child link="medium_left_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

 <joint type="continuous" name="medium_right_wheel_hinge">
    <origin xyz="0 -0.3 0" rpy="0 0 0"/>
    <child link="medium_right_wheel"/>
    <parent link="base_link"/>		
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <joint type="continuous" name="front_left_wheel_hinge">
    <origin xyz="0.5 0.3 0" rpy="0 0 0"/>
    <child link="front_left_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>
  <joint type="continuous" name="front_right_wheel_hinge">
    <origin xyz="0.5 -0.3 0" rpy="0 0 0"/>
    <child link="front_right_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>


  <joint type="continuous" name="back_left_wheel_hinge">
    <origin xyz="-0.5 0.3 0" rpy="0 0 0"/>
    <child link="back_left_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>


 <joint type="continuous" name="back_right_wheel_hinge">
    <origin xyz="-0.5 -0.3 0" rpy="0 0 0"/>
    <child link="back_right_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>
<link name="left_camera">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
    </geometry>
    </collision>

    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
    </geometry>
    <material name="grey"/>
    </visual>

    <inertial>
       <mass value="${cameraMass}" />
       <origin xyz="0 0 0" rpy="0 0 0" />
       <box_inertia m="${cameraMass}" x= "${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
       <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>
<link name="right_camera">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
    </geometry>
    </collision>

    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
    </geometry>
    <material name="grey"/>
    </visual>

    <inertial>
       <mass value="${cameraMass}" />
       <origin xyz="0 0 0" rpy="0 0 0" />
       <box_inertia m="${cameraMass}" x= "${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
       <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>
<link name="stereocamera_baselink">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.25 .35 0.1"/>
    </geometry>
    </collision>

    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.25 0.35 0.1"/>
    </geometry>
    <material name="black"/>
    </visual>

    <inertial>
       <mass value="0.1" />
       <origin xyz="0 0 0" rpy="0 0 0" />
       <box_inertia m="0.1" x= "0.035" y="0.025" z="0.01" />
       <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>

    <link name="imu_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
            <material name="red"/>
        </visual>
        <inertial>
            <mass value="0.001" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.00000015" ixy="0" ixz="0" iyy="0.00000015" iyz="0" izz="0.00000015" />
        </inertial>
</link>

<joint name="imu_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="0 0 0" rpy="0 0 0"/>
  <parent link="stereocamera_baselink"/>
  <child link="imu_link"/>
</joint>

<joint name="stereocamera_baselink_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="0.28 0 0.2" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="stereocamera_baselink"/>
</joint>
<joint name="left_camera_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="0.1 0.15 0" rpy="0 0 0"/>
  <parent link="stereocamera_baselink"/>
  <child link="left_camera"/>
</joint>

<joint name="right_camera_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="0.1 -0.15 0" rpy="0 0 0"/>
  <parent link="stereocamera_baselink"/>
  <child link="right_camera"/>
</joint>

  <joint name="base_laser_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz=".45 0 0.21" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="base_laser"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="base_laser">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.1 0.1 0.1"/>
    </geometry>
      <!--geometry>
        <mesh filename="/home/ali/mybot_ws/src/mybot_description/meshes/hokuyo.dae"/>
      </geometry-->
    <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>


<link name="mainboard">
    <collision>
    <origin xyz="0 -0.4 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.25 .35 0.1"/>
    </geometry>
    </collision>

    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.25 0.35 0.1"/>
    </geometry>
    <material name="red"/>
    </visual>

    <inertial>
       <mass value="2" />
       <origin xyz="0 0 0" rpy="0 0 0" />
        <box_inertia m="0.3" x= "0.1" y="0.1" z="0.1" />
       <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>

<joint name="mainboard_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="-0.38 0 0" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="mainboard"/>
</joint>
</robot>
